-- MySQL Script generated by MySQL Workbench
-- 2018年10月23日 星期二 19时04分19秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema america_used_car_estimate
-- -----------------------------------------------------
-- 美国二手车估值系统数据库

-- -----------------------------------------------------
-- Schema america_used_car_estimate
--
-- 美国二手车估值系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `america_used_car_estimate` DEFAULT CHARACTER SET utf8 ;
USE `america_used_car_estimate` ;

-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_state_city_zip_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_state_city_zip_code` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `str_zip_code` VARCHAR(12) NOT NULL COMMENT '邮编',
  `str_state` VARCHAR(64) NOT NULL COMMENT '州',
  `str_state_simple` VARCHAR(4) NOT NULL COMMENT '州简写',
  `str_county` VARCHAR(64) NULL COMMENT '区/县',
  `str_city` VARCHAR(64) NULL COMMENT '城市',
  `f_latitude` DECIMAL(6,6) NULL COMMENT '纬度',
  `f_longitude` DECIMAL(6,6) NULL COMMENT '经度',
  `t_create` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `zip_code_UNIQUE` (`str_zip_code` ASC),
  INDEX `state_simple_INDEX` (`str_state_simple` ASC))
ENGINE = InnoDB
COMMENT = '州-区/县-城市邮编,以及经纬度.';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_car_style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_car_style` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '标准汽车款型库';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_origin_crawl_new_car_model_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_origin_crawl_new_car_model_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '新车车型库';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_origin_crawl_carmax_car_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_origin_crawl_carmax_car_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `str_make` VARCHAR(32) NOT NULL COMMENT '品牌\n',
  `str_model` VARCHAR(32) NOT NULL COMMENT '车型',
  `str_detail` VARCHAR(64) NOT NULL COMMENT '详情',
  `str_shop` VARCHAR(64) NULL COMMENT '商店名称',
  `str_addr` VARCHAR(64) NOT NULL COMMENT '地址.地址.例子:Long Beach, CA',
  `n_price` INT(12) NOT NULL COMMENT 'carmax一口价',
  `n_stock` INT(12) NULL COMMENT 'stock编号',
  `n_mileage` INT(12) NULL COMMENT '英里数',
  `str_mpg` VARCHAR(32) NULL COMMENT '城市/高速公路',
  `str_color_exterior` VARCHAR(32) NULL COMMENT '外饰颜色',
  `str_color_interior` VARCHAR(32) NULL COMMENT '内饰颜色',
  `str_transmission` VARCHAR(32) NULL COMMENT '变速器',
  `str_drive` VARCHAR(16) NULL COMMENT '驱动',
  `str_engine` VARCHAR(16) NULL COMMENT '引擎\n',
  `str_cylinders` VARCHAR(12) NULL COMMENT '气缸',
  `str_horsepower` VARCHAR(45) NULL COMMENT '马力',
  `str_torque` VARCHAR(45) NULL COMMENT '扭矩',
  `str_prior_use` VARCHAR(45) NULL COMMENT '之前使用方',
  `str_url` VARCHAR(256) NULL COMMENT '详情页地址',
  `str_deal_status_code` TINYINT(2) NULL COMMENT '交易状态.S 在售,R 已交易.',
  `t_pub` DATETIME NOT NULL COMMENT '发布时间',
  `t_sold` DATETIME NULL COMMENT '交易时间',
  `t_update` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `t_pub_INDEX` (`t_pub` ASC),
  INDEX `t_update_INDEX` (`t_update` ASC))
ENGINE = InnoDB
COMMENT = 'carmax原始车源数据';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_origin_crawl_autotrader_car_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_origin_crawl_autotrader_car_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `str_make` VARCHAR(32) NOT NULL COMMENT '品牌\n',
  `str_model` VARCHAR(32) NOT NULL COMMENT '车型',
  `str_detail` VARCHAR(64) NOT NULL COMMENT '详情',
  `str_color` VARCHAR(32) NULL COMMENT '颜色',
  `n_price` INT(12) NOT NULL COMMENT '交易价格',
  `n_mileage` INT(12) NOT NULL COMMENT '英里数',
  `str_drive_type` VARCHAR(64) NULL COMMENT '驱动类型',
  `str_engine` VARCHAR(64) NULL COMMENT '引擎',
  `str_transmission` VARCHAR(64) NULL COMMENT '变速器',
  `str_fuel_type` VARCHAR(64) NULL COMMENT '燃料类型',
  `str_mpg` VARCHAR(32) NULL COMMENT '城市/高速公路',
  `str_interior` VARCHAR(45) NULL COMMENT '内饰',
  `str_exterior` VARCHAR(45) NULL COMMENT '外饰',
  `str_seller_type_code` TINYINT(2) NOT NULL COMMENT '卖方类型.D 车商,P 个人.',
  `str_dealer` VARCHAR(45) NULL COMMENT '车商名称.是车商就填车商名称,是个人就填private seller.',
  `str_addr` VARCHAR(64) NOT NULL COMMENT '地址.例子:Long Beach, CA',
  `str_phone` VARCHAR(16) NULL COMMENT '电话',
  `str_url` VARCHAR(256) NULL COMMENT '详情页地址',
  `str_deal_status_code` TINYINT(2) NULL COMMENT '交易状态.S 在售,R 已交易.',
  `t_pub` DATETIME NOT NULL COMMENT '发布时间',
  `t_sold` DATETIME NULL COMMENT '交易时间',
  `t_update` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `t_pub_INDEX` (`t_pub` ASC),
  INDEX `t_update_INDEX` (`t_update` ASC))
ENGINE = InnoDB
COMMENT = 'autotrader原始车源数据';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_origin_crawl_compete_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_origin_crawl_compete_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '竞品对比原始抓取数据';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_compete_estimate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_compete_estimate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '竞品估值';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_used_car_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_used_car_platform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '二手车平台';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_compete_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_compete_platform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '竞品平台';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_used_car_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_used_car_condition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '二手车车况';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_car_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_car_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '标准汽车车型库';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_standard_car_make`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_standard_car_make` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '标准汽车品牌库';


-- -----------------------------------------------------
-- Table `america_used_car_estimate`.`base_origin_crawl_car_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `america_used_car_estimate`.`base_origin_crawl_car_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `str_make` VARCHAR(32) NOT NULL COMMENT '品牌',
  `str_model` VARCHAR(32) NOT NULL COMMENT '车型',
  `str_style` VARCHAR(64) NOT NULL COMMENT '款型',
  `str_category` VARCHAR(32) NOT NULL COMMENT '车身分类',
  `n_year` INT(4) NOT NULL COMMENT '上市年款',
  `text_mechanical` TEXT NOT NULL COMMENT '机械配置',
  `text_interior` TEXT NOT NULL COMMENT '内饰',
  `text_exterior` TEXT NOT NULL COMMENT '外饰',
  `text_packages` TEXT NOT NULL COMMENT '附件包',
  `text_color` TEXT NOT NULL COMMENT '基本颜色',
  `t_create` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `t_create_INDEX` (`t_create` ASC))
ENGINE = InnoDB
COMMENT = '原始汽车品牌车型款型抓取数据,默认抓取kbb.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
